### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Bartyspace** [tsparticles/astro#21]
Hi, am having issue with tsparticles script i my project.

![problem tsparticles1](https://github.com/tsparticles/astro/assets/160775685/3c0e45eb-684d-42f0-926d-85804e7a6bda)
![problem tsparticles2](https://github.com/tsparticles/astro/assets/160775685/99d538d2-545a-4715-aa54-83eda0527fc8)
![problemtsparticles3](https://github.com/tsparticles/astro/assets/160775685/f93d2af6-a8d7-4a2b-af5e-874ffe136858)
![problemtsparticles4](https://github.com/tsparticles/astro/assets/160775685/b0bd6404-9620-41f0-be67-db9da6681f53)

Can u help me?

**Comment by matteobruni** [comment]
`particlesInit` is not part of window type, you need to declare a new property there like this: https://stackoverflow.com/questions/12709074/how-do-you-explicitly-set-a-new-property-on-window-in-typescript

about the other error, what tsparticles packages are you using and which version? `astro-particles` doesn't work with `tsparticles` v3 yet.

**Comment by Bartyspace** [comment]
I solved the first problem, So how can i use tsParticles in Astro? With React?

**Comment by matteobruni** [comment]
> I solved the first problem, So how can i use tsParticles in Astro? With React?

Use version 2, if you don’t need v3 features it’s fine.

**Comment by matteobruni** [comment]
> I uninstall all modules and installed astro-particles. Now i don´t know how to install tsparticles v2.

`npm install tsparticles@2`

**Comment by Bartyspace** [comment]
I tried everything. Now i have astro-particles and tsparticles@2. Another problem showed up.
![Snímek obrazovky 2024-03-15 193908](https://github.com/tsparticles/astro/assets/160775685/171e5596-ea56-491c-aa20-29f7c4fdd850)

**Comment by Bartyspace** [comment]
I solved it. Solution was tsParticles.

**Comment by Bartyspace** [comment]
I solved. Ty for your help. I am do happy after four days of trying. 😆 
![Snímek obrazovky 2024-03-15 200738](https://github.com/tsparticles/astro/assets/160775685/cf27fbf0-04c6-4c49-9d1e-e078ccfd24fe)
