### ISSUE TITLE
How do I switch themes using Astro?

### ISSUE THREAD

**Issue by KenjiPcx** [tsparticles/astro#3]
Hi, I have been trying to switch themes using ts-particles, I have seen your codepen https://codepen.io/matteobruni/pen/MWopjRP for switching themes using vanilla js, but I am wondering how to do it in Astro, because I can't get the theme container

**Comment by matteobruni** [comment]
Since there's no `particlesLoaded` function, you can get tsParticles running instances using `tsParticles.domItem(<index>)`, importing `tsParticles` like in the readme. I haven't found a way to pass functions to an Astro component, so that's the only way for now.

**Comment by KenjiPcx** [comment]
Oh nice, I'll try it out 😃 thanks

**Comment by KenjiPcx** [comment]
Tried this out and it works 🔥, closing it
